In [2]:
import pandas as pd
import numpy as np

In [4]:
## Python Dictionaries and DataFrames
student_data = {
    "Name":["JOHN", "JANE", "JAMES", "JACK", "JILL", "ANDREW"],
    "Science":[90, 85, 95, 80, 70, 75],
    "Math":[85, 90, 80, 75, 95, 100],
    "Gender":["Male", "Female", "Male", "Male", "Female", "Male"]
}
students = pd.DataFrame(student_data)
students

     Name  Science  Math  Gender
0    JOHN       90    85    Male
1    JANE       85    90  Female
2   JAMES       95    80    Male
3    JACK       80    75    Male
4    JILL       70    95  Female
5  ANDREW       75   100    Male

In [5]:
students.shape

(6, 4)

In [6]:
students.describe()

         Science        Math
count   6.000000    6.000000
mean   82.500000   87.500000
std     9.354143    9.354143
min    70.000000   75.000000
25%    76.250000   81.250000
50%    82.500000   87.500000
75%    88.750000   93.750000
max    95.000000  100.000000

In [1]:
students. info()

NameError: name 'students' is not defined